kind: pipeline
type: docker
name: awsbuilders-poweron

clone:
  disable: true

steps:
- name: start-aws-instances
  pull: always
  image: amazon/aws-cli
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  commands:
    - aws ec2 start-instances --region eu-north-1 --instance-ids i-01e3d598710a23947 i-02bb3cbe63a2b3fef

trigger:
  branch:
    include:
    - master
    - main
  event:
    include:
    - push
    - pull_request
    - tag

---
#######################################################################################
# OS4 base GCC11 Adtools for Amd64 ####################################################
#
kind: pipeline
type: docker
name: build-os4-base-gcc11-adtools-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: os4-base-gcc11-adtools-amd64
  image: plugins/docker
  pull: always
  settings:
    repo: walkero/amigagccondocker
    tags:
      - os4-base-gcc11-adtools-amd64
    cache_from:
      - walkero/amigagccondocker:os4-base-gcc11-adtools-amd64
    dockerfile: base/os4/Dockerfile
    context: base/os4
    purge: true
    compress: true
    # squash: true
    # dry_run: true
    build_args:
      - OS=os4
      - CLIB2_REPO=adtools
      - GCC_VER=11
      - FILES_PATH=./files
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

trigger:
  branch:
    include:
    - master
    - main
  event:
    include:
    - push

depends_on:
  - awsbuilders-poweron

node:
  agents: awsbuilders

---
#######################################################################################
# OS4 base GCC11 Adtools for Arm64 ####################################################
#
kind: pipeline
type: docker
name: build-os4-base-gcc11-adtools-arm64

platform:
  arch: arm64
  os: linux

steps:
- name: os4-base-gcc11-adtools-arm64
  image: plugins/docker
  pull: always
  settings:
    repo: walkero/amigagccondocker
    tags:
      - os4-base-gcc11-adtools-arm64
    cache_from:
      - walkero/amigagccondocker:os4-base-gcc11-adtools-arm64
    dockerfile: base/os4/Dockerfile
    context: base/os4
    purge: true
    compress: true
    # squash: true
    # dry_run: true
    build_args:
      - OS=os4
      - CLIB2_REPO=adtools
      - GCC_VER=11
      - FILES_PATH=./files
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

trigger:
  branch:
    include:
    - master
    - main
  event:
    include:
    - push

depends_on:
  - awsbuilders-poweron

node:
  agents: awsbuilders

---
#######################################################################################
# OS4 base GCC11 Adtools Manifest #####################################################
#
kind: pipeline
name: build-manifest-base-os4

steps:
- name: manifest-base-os4
  image: plugins/manifest
  settings:
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
    target: walkero/amigagccondocker:os4-base-gcc11-adtools
    template: walkero/amigagccondocker:os4-base-gcc11-adtools-ARCH
    platforms:
      - linux/amd64
      - linux/arm64

depends_on:
  - awsbuilders-poweron
  - build-os4-base-gcc11-adtools-amd64
  - build-os4-base-gcc11-adtools-arm64

trigger:
  branch:
    include:
    - master
    - main
  event:
    include:
    - push

node:
  agents: awsbuilders