kind: pipeline
type: docker
name: awsbuilders-poweron

clone:
  disable: true

steps:
- name: start-aws-instances
  pull: always
  image: amazon/aws-cli
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  commands:
    - aws ec2 start-instances --region eu-north-1 --instance-ids i-01e3d598710a23947

trigger:
  branch:
    include:
    - master
    - main
  event:
    include:
    - push
    - pull_request
    - tag

---

kind: pipeline
type: docker
name: build-os4-gcc11-adtools

steps:
# - name: os4-gcc11-adtools
#   image: plugins/docker
#   pull: always
#   settings:
#     repo: walkero/amigagccondocker
#     tags:
#       - os4-gcc11-adtools
#     cache_from:
#       - walkero/amigagccondocker:os4-gcc11-adtools
#     dockerfile: os4.Dockerfile
#     build_args:
#       - OS=os4
#       - CLIB2_REPO=adtools
#       - GCC_VER=11
#     dry_run: true
# - name: os4-gcc11-adtools-tests
#   image: walkero/amigagccondocker:os4-gcc11-adtools
#   commands:
#     - cd /opt/code/tests/os4
#     - su amidev
#     - ppc-amigaos-gcc -o test test.c
#     - ppc-amigaos-g++ -athread=native test2.c -o test2
#     - ppc-amigaos-gcc -gstabs -athread=native sdl_example.c -o sdl_example -I${SDL2_INC} -L${SDL2_LIB} -lSDL2 -lpthread
#     - ppc-amigaos-gcc -D__USE_INLINE__ httpget.c -o httpget
#     - ppc-amigaos-gcc curl.c -o curl -I$LIB_CURL_INC -L$LIB_CURL_CLIB -lcurl
#   depends_on:
#     - os4-gcc11-adtools
- name: os4-gcc11-adtools-push
  image: plugins/docker
  settings:
    repo: walkero/amigagccondocker
    tags:
      - os4-gcc11-adtools
    cache_from:
      - walkero/amigagccondocker:os4-gcc11-adtools
    dockerfile: os4.Dockerfile
    purge: true
    build_args:
      - OS=os4
      - CLIB2_REPO=adtools
      - GCC_VER=11
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
  # depends_on:
  #   - os4-gcc11-adtools-tests

trigger:
  branch:
    include:
    - master
    - main
  event:
    include:
    - push

depends_on:
  - awsbuilders-poweron

node:
  agents: awsbuilders

# ---

# kind: pipeline
# type: docker
# name: build-os4-gcc11-afxgroup

# steps:
# - name: os4-gcc11-afxgroup
#   image: plugins/docker
#   pull: always
#   settings:
#     repo: walkero/amigagccondocker
#     tags:
#       - os4-gcc11-afxgroup
#     cache_from:
#       - walkero/amigagccondocker:os4-gcc11-afxgroup
#     dockerfile: os4.Dockerfile
#     build_args:
#       - OS=os4
#       - CLIB2_REPO=afxgroup
#       - GCC_VER=11
#     dry_run: true
# - name: os4-gcc11-afxgroup-tests
#   image: walkero/amigagccondocker:os4-gcc11-afxgroup
#   commands:
#     - cd /opt/code/tests/os4
#     - su amidev
#     - ppc-amigaos-gcc -o test test.c
#     - ppc-amigaos-g++ -athread=native test2.c -o test2
#     - ppc-amigaos-gcc -gstabs -athread=native sdl_example.c -o sdl_example -I${SDL2_INC} -L${SDL2_LIB} -lSDL2 -lpthread
#     - ppc-amigaos-gcc -D__USE_INLINE__ httpget.c -o httpget
#     - ppc-amigaos-gcc curl.c -o curl -I$LIB_CURL_INC -L$LIB_CURL_CLIB -lcurl
#   depends_on:
#     - os4-gcc11-afxgroup
# - name: os4-gcc11-afxgroup-push
#   image: plugins/docker
#   settings:
#     repo: walkero/amigagccondocker
#     tags:
#       - os4-gcc11-afxgroup
#     cache_from:
#       - walkero/amigagccondocker:os4-gcc11-afxgroup
#     dockerfile: os4.Dockerfile
#     purge: true
#     build_args:
#       - OS=os4
#       - CLIB2_REPO=adtools
#       - GCC_VER=11
#     username:
#       from_secret: DOCKERHUB_USERNAME
#     password:
#       from_secret: DOCKERHUB_PASSWORD
#     depends_on:
#       - os4-gcc11-adtools-tests
# trigger:
#   branch:
#     include:
#     - master
#     - main
#   event:
#     include:
#     - push

# depends_on:
#   - awsbuilders-poweron

# node:
#   agents: awsbuilders
