labels:
  role: awsbuilder
  platform: linux/arm64

steps:
  - name: build-ppc-morphos-gcc
    image: plugins/docker
    settings:
      repo: walkero/amigagccondocker
      # registry: https://index.docker.io/v1/
      dockerfile: ppc-morphos/Dockerfile
      context: ppc-morphos
      compress: true
      purge: true
      # dry-run: true
      # cache_from:
      #   - walkero/amigagccondocker:os4-gcc${GCC}-arm64
      no-cache: true
      tags:
        - mos-gcc-arm64
        - mos-gcc-${CI_COMMIT_TAG##mos-}-arm64
      username:
        from_secret: DOCKERHUB_USERNAME
      password:
        from_secret: DOCKERHUB_PASSWORD

when:
  - branch: main
    event: [tag]
    ref: refs/tags/mos-*

depends_on:
  - aws-poweron