labels:
  role: awsbuilder
  platform: linux/amd64

steps:
  - name: build-ppc-amigaos-gcc11
    image: plugins/docker
    settings:
      repo: walkero/amigagccondocker
      # registry: https://index.docker.io/v1/
      dockerfile: ppc-amigaos/Dockerfile
      context: ppc-amigaos
      compress: true
      purge: true
      # dry-run: true
      cache_from:
        - walkero/amigagccondocker:os4-gcc11-amd64
      build_args:
        - OS=os4
        - GCC_VER=11
      tags:
        - os4-gcc11-amd64
        - os4-gcc11-${CI_COMMIT_TAG}-amd64
      username:
        from_secret: DOCKERHUB_USERNAME
      password:
        from_secret: DOCKERHUB_PASSWORD

when:
  - branch: main
    event: [tag]

depends_on:
  - aws-poweron