labels:
  role: generic

matrix:
  GCC:
    - 11
    - 8
    - 6

skip_clone: true

steps:
  - name: build-ppc-amigaos-latest-manifest
    image: plugins/manifest
    environment:
      PULLREQUEST_DRONE_PULL_REQUEST: 0
    settings:
      target: "walkero/amigagccondocker:os4-gcc${GCC}"
      template: "walkero/amigagccondocker:os4-gcc${GCC}-ARCH"
      platforms:
        - linux/amd64
        - linux/arm64
      username:
        from_secret: DOCKERHUB_USERNAME
      password:
        from_secret: DOCKERHUB_PASSWORD
  - name: build-ppc-amigaos-versioned-manifest
    image: plugins/manifest
    environment:
      PULLREQUEST_DRONE_PULL_REQUEST: 0
    settings:
      target: "walkero/amigagccondocker:os4-gcc${GCC}-${CI_COMMIT_TAG##os4-}"
      template: "walkero/amigagccondocker:os4-gcc${GCC}-${CI_COMMIT_TAG##os4-}-ARCH"
      platforms:
        - linux/amd64
        - linux/arm64
      username:
        from_secret: DOCKERHUB_USERNAME
      password:
        from_secret: DOCKERHUB_PASSWORD

when:
  - branch: main
    event: [tag]
    ref: refs/tags/os4-*

depends_on:
  - build-amd64
  - build-arm64