labels:
  role: generic

skip_clone: true

steps:
  - name: build-ppc-morphos-latest-manifest
    image: plugins/manifest
    environment:
      PULLREQUEST_DRONE_PULL_REQUEST: 0
    settings:
      target: "walkero/amigagccondocker:mos-gcc"
      template: "walkero/amigagccondocker:mos-gcc-ARCH"
      platforms:
        - linux/amd64
        - linux/arm64
      username:
        from_secret: DOCKERHUB_USERNAME
      password:
        from_secret: DOCKERHUB_PASSWORD
  - name: build-ppc-morphos-versioned-manifest
    image: plugins/manifest
    environment:
      PULLREQUEST_DRONE_PULL_REQUEST: 0
    settings:
      target: "walkero/amigagccondocker:mos-gcc-${CI_COMMIT_TAG##mos-}"
      template: "walkero/amigagccondocker:mos-gcc-${CI_COMMIT_TAG##mos-}-ARCH"
      platforms:
        - linux/amd64
        - linux/arm64
      username:
        from_secret: DOCKERHUB_USERNAME
      password:
        from_secret: DOCKERHUB_PASSWORD

when:
  - branch: main
    event: [tag]
    ref: refs/tags/mos-*

depends_on:
  - build-mos-amd64
  - build-mos-arm64